#ifndef _REDIS_ERRORS_H_
#define _REDIS_ERRORS_H_

typedef enum
{
  SUCCESS,
  SOCKET_CREATE_FAILED,
  SOCKET_CONNECT_FAILED,
  SOCKET_CLOSE_FAILED,
  SOCKET_READ_FAILED,
  SOCKET_WRITE_FAILED,
  SOCKET_ADDRESS_TRANSLATION_FAILED,
  SOCKET_TIMEOUT,
  SOCKET_MEMORY_FAILED,
} return_code;

#endif
